import { NextRequest, NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { lineAuthSchema } from "@/lib/validations/auth";
import { createRateLimiter, checkRateLimit, getClientIp } from "@/lib/rate-limit";
import { signAuthToken } from "@/lib/auth";
import { adminQuery, profiles } from "@/lib/db/index";
import type { Tx } from "@/lib/db/index";
import { upload } from "@/lib/storage/index";

const limiter = createRateLimiter(10, "1 m");

// ---------------------------------------------------------------------------
// LINE id_token verification — keep the exact fetch shape as before.
// ---------------------------------------------------------------------------
async function verifyLineIdToken(
  idToken: string
): Promise<{ sub: string; name: string; picture?: string; email?: string } | null> {
  if (process.env.E2E_TEST_MODE === "true" && idToken === "e2e-test-token") {
    return { sub: "e2e-test-line-sub", name: "E2E Test User", picture: "" };
  }

  const res = await fetch("https://api.line.me/oauth2/v2.1/verify", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      id_token: idToken,
      client_id: process.env.LINE_CHANNEL_ID!,
    }),
  });

  if (!res.ok) return null;

  const payload = await res.json();
  return {
    sub: payload.sub,
    name: payload.name,
    picture: payload.picture ?? undefined,
    ...(payload.email ? { email: payload.email } : {}),
  };
}

// ---------------------------------------------------------------------------
// Avatar re-upload — fetch LINE CDN picture and store in user-photos bucket.
// Falls back to LINE CDN URL on any failure.
// ---------------------------------------------------------------------------
async function reuploadAvatar(userId: string, pictureUrl: string): Promise<string> {
  try {
    const imgRes = await fetch(pictureUrl);
    const buffer = Buffer.from(await imgRes.arrayBuffer());
    const storedUrl = await upload("user-photos", `avatars/${userId}.jpg`, buffer, {
      upsert: true,
      contentType: "image/jpeg",
    });
    return storedUrl;
  } catch {
    // Network error or storage failure — fall back to LINE CDN URL
    return pictureUrl;
  }
}

// ---------------------------------------------------------------------------
// POST /api/auth/line
//
// Route order: rate-limit → validate → LINE verify → db → sign
// GoTrue (supabase.auth.admin.*) removed entirely.
// profiles is now the sole user table; UUID generated by the app.
// ---------------------------------------------------------------------------
export async function POST(request: NextRequest) {
  try {
    // 1. Rate limit
    const rateLimitResponse = await checkRateLimit(limiter, getClientIp(request));
    if (rateLimitResponse) return rateLimitResponse;

    // 2. Validate body
    const body = await request.json().catch(() => null);
    const parsed = lineAuthSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: parsed.error.issues[0]?.message ?? "Invalid request" },
        { status: 400 }
      );
    }

    // 3. Verify LINE id_token
    const lineProfile = await verifyLineIdToken(parsed.data.idToken);
    if (!lineProfile) {
      return NextResponse.json({ error: "Invalid LINE token" }, { status: 401 });
    }

    // 4. DB — adminQuery is allowlisted call site #1
    const profile = await adminQuery(async (tx: Tx) => {
      // Look up existing profile by line_user_id
      const existing = await tx
        .select()
        .from(profiles)
        .where(eq(profiles.lineUserId, lineProfile.sub))
        .limit(1);

      if (existing.length > 0) {
        const row = existing[0];

        // Refresh display name + avatar if they changed; backfill email when
        // LINE supplies one and the column is still null.
        const needsUpdate =
          row.lineDisplayName !== lineProfile.name || (lineProfile.email && !row.email);

        if (!needsUpdate) return row;

        const updates: Partial<typeof profiles.$inferInsert> = {};
        if (row.lineDisplayName !== lineProfile.name) {
          updates.lineDisplayName = lineProfile.name;
        }
        if (lineProfile.email && !row.email) {
          updates.email = lineProfile.email;
        }

        const updated = await tx
          .update(profiles)
          .set(updates)
          .where(eq(profiles.id, row.id))
          .returning();

        return updated[0] ?? row;
      }

      // New user — generate UUID in the app (profiles.id has NO default).
      const userId = crypto.randomUUID();

      // Avatar re-upload (new-user only — keeps CDN URL from expiring).
      let avatarUrl: string | undefined = lineProfile.picture;
      if (lineProfile.picture) {
        avatarUrl = await reuploadAvatar(userId, lineProfile.picture);
      }

      const inserted = await tx
        .insert(profiles)
        .values({
          id: userId,
          lineUserId: lineProfile.sub,
          lineDisplayName: lineProfile.name,
          fullName: lineProfile.name,
          avatarUrl: avatarUrl ?? null,
          // Real email only — synthetic @line.local addresses are dead.
          ...(lineProfile.email ? { email: lineProfile.email } : {}),
          createdAt: new Date(),
        })
        .returning();

      if (!inserted[0]) {
        throw new Error("Profile insert returned no rows");
      }
      return inserted[0];
    });

    // 5. Sign self-issued JWT
    const accessToken = await signAuthToken(profile.id);

    return NextResponse.json({
      access_token: accessToken,
      user: {
        id: profile.id,
        line_user_id: profile.lineUserId,
        line_display_name: profile.lineDisplayName,
        avatar_url: profile.avatarUrl,
        email: profile.email,
        full_name: profile.fullName,
        created_at: profile.createdAt,
      },
    });
  } catch (err) {
    console.error("[auth/line] Unhandled error:", err instanceof Error ? err.message : "unknown");
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
